import { describe, expect, it } from 'vitest';
import { readFileSync, writeFileSync } from 'node:fs';
import { ALL_HEROES } from '../data/index';
import { heroWorldSize, inBand, SIZE_BANDS, type ResolvedWorldSize } from '../engine/world-size';
import { AMBIENT_CRITTERS, DRESSING_PROP_SIZES, TOWN_BUILDING_SIZE, FOLIAGE_SIZES } from '../data/world/props';
import { TREE_MODELS, ROCK_MODELS, TOWN_BUILDINGS } from '../engine/terrain';
import type { SizeClass, WorldSize } from '../core/types';

// ============================================================
// OVERWORLD_PLANNING §5.6 / §10.4: the build pipeline (build_assets.mjs, a plain
// .mjs with no TS runtime) needs each shipped GLB's declared fit target so it can
// stamp post-fit `dimsM` into the manifest (closing the §9.5 gate). This test is
// the generator + the guard: it computes the authoritative path -> WorldSize map
// from the same resolver the renderer uses and asserts the committed JSON matches.
// Refresh with: UPDATE_WORLD_SIZES=1 npx vitest run src/test/asset-world-sizes.test.ts
// ============================================================

const MAP_PATH = 'scripts/assets/world-sizes.generated.json';

interface SizeMapEntry {
  heightM: number;
  sizeClass: SizeClass;
  pose: string;
  source: string;
}

const round = (n: number): number => +n.toFixed(4);

function entryFrom(ws: ResolvedWorldSize | WorldSize, source: string): SizeMapEntry {
  return {
    heightM: round(ws.heightM),
    sizeClass: (ws.sizeClass ?? 'prop') as SizeClass,
    pose: ws.pose ?? 'static',
    source
  };
}

// Dressing-prop keys -> the authored filenames already on disk.
const DRESSING_FILES: Record<keyof typeof DRESSING_PROP_SIZES, string> = {
  well: 'well',
  cart: 'cart',
  barrel: 'barrel',
  market: 'market_stand_1'
};

function buildSizeMap(): Record<string, SizeMapEntry> {
  const map: Record<string, SizeMapEntry> = {};
  // Per-hero GLBs (one file per hero, fit to 1.8 x scale).
  for (const hero of ALL_HEROES) map[`heroes/${hero.id}.glb`] = entryFrom(heroWorldSize(hero), 'hero');
  // Ambient critters.
  for (const c of AMBIENT_CRITTERS) map[c.url.replace(/^\/assets\//, '')] = entryFrom(c.worldSize, 'critter');
  // Town dressing props.
  for (const [key, file] of Object.entries(DRESSING_FILES)) {
    map[`props/town/${file}.glb`] = entryFrom(DRESSING_PROP_SIZES[key as keyof typeof DRESSING_PROP_SIZES], 'prop');
  }
  // Town buildings (all share the structure fit target).
  for (const name of TOWN_BUILDINGS) map[`props/town/${name}.glb`] = entryFrom(TOWN_BUILDING_SIZE, 'building');
  // Foliage: trees + rocks.
  const trees = new Set(Object.values(TREE_MODELS).flat());
  for (const name of trees) map[`props/foliage/${name}.glb`] = entryFrom(FOLIAGE_SIZES.tree, 'foliage');
  for (const name of ROCK_MODELS) map[`props/foliage/${name}.glb`] = entryFrom(FOLIAGE_SIZES.rock, 'foliage');
  // Stable key order so the committed JSON is diff-friendly.
  return Object.fromEntries(Object.keys(map).sort().map((k) => [k, map[k]]));
}

describe('asset world sizes (OVERWORLD_PLANNING §5.6)', () => {
  const sizes = buildSizeMap();

  it('every mapped GLB declares an in-band height', () => {
    expect(Object.keys(sizes).length).toBeGreaterThan(80);
    for (const [path, entry] of Object.entries(sizes)) {
      expect(SIZE_BANDS[entry.sizeClass], `${path}: class ${entry.sizeClass}`).toBeDefined();
      expect(inBand(entry.sizeClass, entry.heightM), `${path}: ${entry.heightM}m out of ${entry.sizeClass} band`).toBe(true);
    }
  });

  it('the committed size map is in sync with the resolver', () => {
    const payload = {
      _comment: 'GENERATED by src/test/asset-world-sizes.test.ts. Path -> declared WorldSize the asset build fits to (OVERWORLD_PLANNING §5.6). Refresh: UPDATE_WORLD_SIZES=1 npx vitest run src/test/asset-world-sizes.test.ts',
      version: 1,
      sizes
    };
    if (process.env.UPDATE_WORLD_SIZES) {
      writeFileSync(MAP_PATH, `${JSON.stringify(payload, null, 2)}\n`);
    }
    let onDisk: { sizes?: Record<string, SizeMapEntry> } | null = null;
    try {
      onDisk = JSON.parse(readFileSync(MAP_PATH, 'utf8'));
    } catch {
      onDisk = null;
    }
    expect(onDisk, `${MAP_PATH} missing — run UPDATE_WORLD_SIZES=1 to generate`).not.toBeNull();
    expect(onDisk!.sizes, 'size map drifted — run UPDATE_WORLD_SIZES=1 to refresh').toEqual(sizes);
  });
});
